ARDUINO_DIR = /usr/share/arduino
USER_LIB_PATH = /home/arm/arduino_project/libraries
ARDUINO_LIBS = ros_lib Adafruit_BNO055 Adafruit_BusIO Adafruit_Sensor Grove_Motor_Driver_TB6612FNG Wire BasicLinearAlgebra
BOARD_TAG = nano

# Check for boards.txt in Arduino15 directory
ARDUINO_HARDWARE_PATH = $(HOME)/.arduino15/packages/arduino/hardware/avr/1.8.6

include /usr/share/arduino/Arduino.mk